name: Generate Documentation

on:
  push:
    branches:
      - main  # or the branch of your choice
  pull_request:
    branches:
      - main  # or the branch of your choice

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Generate Sphinx documentation
      run: |
        sphinx-apidoc -o docs/source/ src/
        sphinx-build -b html docs/source docs/build

    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: docs/build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs/build/html
        publish_branch: gh-pages

